model:
  base_learning_rate: 3.0e-6
  target: model.VQGAN.vqgan.VQFlowNet
  params:
    monitor: val/rec_loss
    embed_dim: 3
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 64
      ch_mult: [1,2,2,2,4]  # f = 2 ^ len(ch_mult)
      num_res_blocks: 1
      cond_type: max_cross_attn
      attn_type: max
      attn_resolutions: [16]
      dropout: 0.0 
      load_VFI: 'net_220.pth'
      num_head_channels: -1

    lossconfig:
      target: model.VQGAN.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 20000
        disc_weight: 0.5
        codebook_weight: 1.0 
        perceptual_weight: 1.0

data:
  target: Autoencoder.main.DataModuleFromConfig
  params:
    batch_size: 16 ## per gpu
    num_workers: 0
    wrap: false
    train:
      target: ldm.data.bvi_vimeo.Vimeo90k_triplet
      params:
        db_dir: /home/zo258499/data/vimeo_triplet ## path to vimeo_triplet
        crop_sz: [256,256]
    validation:
      target: ldm.data.bvi_vimeo.Vimeo90k_triplet
      params:
        db_dir: /home/zo258499/data/vimeo_triplet ## path to vimeo_triplet
        train: False
        crop_sz: [256,256]
        augment_s: False
        augment_t: False


lightning:
  callbacks:
    image_logger:
      target: Autoencoder.main.ImageLogger
      params:
        batch_frequency: 10000
        val_batch_frequency: 1000
        max_images: 8
        increase_log_steps: False
        log_images_kwargs: {'N': 1}

  trainer:
    benchmark: True
    max_epochs: -1
    accumulate_grad_batches: 1
